---
cluster.name: "docker-cluster"
network.host: 0.0.0.0

transport.host: 127.0.0.1
http.host: 0.0.0.0
http.port: ${ELK_ELASTICSEARCH_PORT1}

xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true