- type: icmp
  name: "Kibana Service"
  schedule: '@every 10s'
  hosts: 
    - "${ELK_KIBANA_SERVICE_NAME}"
  ipv4: true
  ipv6: true
  mode: any
  timeout: 16s
  wait: 1s
  tags: 
    - "kibana"
    - "elasticsearch"
    - "icmp"
    - "observability"