---
server.port: 5601
server.basePath: "/${ELK_KIBANA_URL}"
server.host: "${ELK_KIBANA_SIMPLE_HOST}"
server.rewriteBasePath: false

elasticsearch.hosts: [ "http://${ELK_ELASTICSEARCH_HOST}" ]
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.username: elastic
elasticsearch.password: ${ELK_ELASTICSEARCH_PASSWORD}