http:
  enabled: true
  host: "0.0.0.0"
  port: ${ELK_HEARTBEAT_PORT}

heartbeat.config.monitors:
  path: ${path.config}/monitors.d/**/*.yml
  reload.enabled: true
  reload.period: 5s

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.kibana:
  host: "http://${ELK_KIBANA_HOST}"

output.elasticsearch:
  hosts: ["${ELK_ELASTICSEARCH_HOST}"]
  preset: balanced
  
processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

logging.level: debug
logging.selectors: ["*"]
logging.to_files: false
logging.to_syslog: false
loggins.metrice.enabled: false
logging.files:
  path: /var/log/heartbeat
  name: heartbeat
  keepfiles: 7
  permissions: 0644
ssl.verification_mode: none