http:
  enabled: true
  host: "0.0.0.0"
  port: ${FILEBEAT_PORT}

filebeat.inputs: 
  - type: filestream
    id: filestream-nginx-logs
    enabled: true
    paths:
      - /usr/share/filebeat/nginx-logs/*.log
  - type: filestream
    id: filestream-app-logs
    enabled: true
    paths:
      - /usr/share/filebeat/app-logs/**/*.log
    # Como cada evento inicia com "====", use esse padrão para delimitar eventos
    multiline.type: pattern
    multiline.pattern: '^===='
    multiline.negate: true
    multiline.match: before

filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
          contains:
            docker.container.image: nginx
          config:
            - module: nginx
              access:
                input:
                  type: docker
                  containers.ids:
                    - "${data.docker.container.id}"
              error:
                input:
                  type: docker
                  containers.ids:
                    - "${data.docker.container.id}"

processors:
  # (Opcional) Remove quebras de linha para que todo o log fique em uma única linha
  - script:
      lang: javascript
      source: >
        function process(event) {
          var msg = event.Get("message");
          if (msg) {
            // Substitui \r\n ou \n por espaço
            event.Put("message", msg.replace(/(\r\n|\n|\r)/gm, " "));
          }
        }
  - script:
      lang: javascript
      source: >
        function process(event) {
          var msg = event.Get("message");
          if (msg) {
            // Remove os códigos ANSI
            event.Put("message", msg.replace(/\x1b\[[0-9;]*m/g, ""));
          }
        }
  - drop_fields:
      fields: ["log.offset"]
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 10s
  reload.enabled: true

output.elasticsearch:
  hosts: ["${ELK_ELASTICSEARCH_HOST}"]
  username: elastic
  password: ${ELK_ELASTICSEARCH_PASSWORD}
  
logging.level: debug
logging.selectors: ["*"]
logging.to_files: false
logging.to_syslog: false
loggins.metrice.enabled: false
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
ssl.verification_mode: none

setup.kibana:
  host: "http://${ELK_KIBANA_HOST}"
  username: elastic
  password: ${ELK_ELASTICSEARCH_PASSWORD}

# setup.dashboards.enabled: true
