- module: docker
  period: 10s
  metricsets:
    - container
    - cpu
    - diskio
    - event
    - healthcheck
    - info
    - image
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true